### ISSUE TITLE
After installation - /login - Error 404 Not Found

### ISSUE THREAD

**Issue by Gadgetroch** [docpht/docpht#3] opened 2019-09-06 19:55 UTC
Good morning,

When i try to login after wizard install, i get this :

The requested URL /login was not found on this server.

I have installed php7.2, i have enabled mod rewrite and headers, and i have this for site config :
```

    <Directory />
     
      AllowOverride All
    </Directory>
    <Location />
      AllowOverride All
        Options +Indexes
    </Location>

```

Thank's for help

**Comment by creecros** [comment] 2019-09-06 20:34
How did you install? i.e. Docker, Composer, manually, etc...
Did you install via the Release files or Master Repo?

Your message appears to suggest that there is no BASE_URL defined. Check your `src/config/config.php` file and make sure the BASE_URL is defined.

`define("BASE_URL","https://adomain.atnachostudio.yo/");`

**Comment by Yongd** [comment] 2019-09-07 15:21
Same issue with Gadgetroch, and the BASE_URL is defined in src/config/config.php, the server is nginx 1.12, php 7.2

**Comment by creecros** [comment] 2019-09-07 15:26
Can you confirm your install is from the master repository or version 1.0.0 release?

**Comment by kenlog** [comment] 2019-09-07 17:50
Hi @Gadgetroch @Yongd, try the following configuration 

path: etc/apache2/sites-enabled/000-default.conf
```
<Directory /var/www/html>
        AllowOverride All
</Directory> 
````
path: etc/apache2/sites-available/000-default.conf  
```
<Directory /var/www/html>
        AllowOverride All
</Directory>
```
sudo a2ensite *
sudo a2enmod rewrite
sudo service apache2 reload

**Comment by Yongd** [comment] 2019-09-09 07:02
my server is nginx, is there have a solution for this?

**Comment by creecros** [comment] 2019-09-09 15:39
Might help: https://github.com/docpht/docpht/blob/master/docker/etc/nginx/nginx.conf

**Comment by Yongd** [comment] 2019-09-10 02:01
@creecros It works, thank you for your help.

**Comment by Gadgetroch** [comment] 2019-09-10 06:30
i will try that tonight

**Comment by Gadgetroch** [comment] 2019-09-10 11:37
Not better...

**Comment by creecros** [comment] 2019-09-10 20:58
Hoping @kenlog answers that one, because I must confess, I do not ever use apache.

**Comment by kenlog** [comment] 2019-09-11 10:16
The cause is probably mod_rewrite. Following the step by step procedure:

**Step 1 - Enabling mod_rewrite**
`$ sudo a2enmod rewrite`
`$ sudo systemctl restart apache2`

**Step 2 - Setting Up .htaccess**
Add the following new block in <VirtualHost *:80> so your configuration file looks like the following
`$ sudo nano /etc/apache2/sites-available/000-default.conf`
```
<VirtualHost *:80>

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

</VirtualHost>
```
**Save and close the file**

Repeat also for sites-enabled
`$ sudo nano /etc/apache2/sites-enabled/000-default.conf`
```
<VirtualHost *:80>

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

</VirtualHost>
```
**Save and close the file and  enable all site confs with a2ensite**
`$ sudo a2ensite *`

**Step 3 - Restart Apache**
`$ sudo systemctl restart apache2`

That's it, @Gadgetroch let us know if it works. Thank you

**Comment by kenlog** [comment] 2019-09-13 07:39
Hi @Gadgetroch some days have passed since the last answer, if you are still interested this would deserve your feedback otherwise I think I should close this issue.

**Comment by Gadgetroch** [comment] 2019-09-13 07:41
Let me just today more, please

**Comment by kenlog** [comment] 2019-09-13 07:42
Agree

**Comment by Gadgetroch** [comment] 2019-09-13 08:11
Sorry but not better...

**Comment by kenlog** [comment] 2019-09-13 09:55
From what you have indicated, let's think about an incorrect configuration of the mod_rewrite module. I need more information to help you solve, for example, what is your server configuration? Do you use a virtual machine manager? Did you install via the Release files or Master Repo? You can provide me with a record of the errors of the lines concerned that could help. Thanks @Gadgetroch

**Comment by kenlog** [comment] 2019-09-17 08:34
@Gadgetroch this deserves your attention, I expect an answer within the day. Otherwise I will close this issue, thanks.

**Closed as completed** 2019-09-17 18:28 UTC
Labels: needs more info
